/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.analysis;

import minigen.syntax3.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAClassDecl(AClassDecl node);
    void caseAFormalDecls(AFormalDecls node);
    void caseAFormalDecl(AFormalDecl node);
    void caseAAdditionalFormalTypes(AAdditionalFormalTypes node);
    void caseAType(AType node);
    void caseAGenericPart(AGenericPart node);
    void caseAGenericTypes(AGenericTypes node);
    void caseAAdditionalTypes(AAdditionalTypes node);
    void caseASuperDecls(ASuperDecls node);
    void caseAAdditionalSupers(AAdditionalSupers node);
    void caseASuperType(ASuperType node);
    void caseASuperGenericPart(ASuperGenericPart node);
    void caseASuperGenericTypes(ASuperGenericTypes node);
    void caseASuperAdditionalTypes(ASuperAdditionalTypes node);
    void caseAIsaInstr(AIsaInstr node);

    void caseTComma(TComma node);
    void caseTLb(TLb node);
    void caseTRb(TRb node);
    void caseTKend(TKend node);
    void caseTKisa(TKisa node);
    void caseTKclass(TKclass node);
    void caseTKsuper(TKsuper node);
    void caseTKnew(TKnew node);
    void caseTName(TName node);
    void caseTBlanks(TBlanks node);
    void caseTComment(TComment node);
    void caseEOF(EOF node);
}
