/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AClassnameInstr extends PInstr
{
    private TKclassname _kclassname_;
    private PExp _exp_;

    public AClassnameInstr()
    {
        // Constructor
    }

    public AClassnameInstr(
        @SuppressWarnings("hiding") TKclassname _kclassname_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setKclassname(_kclassname_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new AClassnameInstr(
            cloneNode(this._kclassname_),
            cloneNode(this._exp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassnameInstr(this);
    }

    public TKclassname getKclassname()
    {
        return this._kclassname_;
    }

    public void setKclassname(TKclassname node)
    {
        if(this._kclassname_ != null)
        {
            this._kclassname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kclassname_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kclassname_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kclassname_ == child)
        {
            this._kclassname_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kclassname_ == oldChild)
        {
            setKclassname((TKclassname) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
