/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import java.util.*;
import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AGenericTypes extends PGenericTypes
{
    private PType _type_;
    private final LinkedList<PAdditionalTypes> _additionalTypes_ = new LinkedList<PAdditionalTypes>();

    public AGenericTypes()
    {
        // Constructor
    }

    public AGenericTypes(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") List<PAdditionalTypes> _additionalTypes_)
    {
        // Constructor
        setType(_type_);

        setAdditionalTypes(_additionalTypes_);

    }

    @Override
    public Object clone()
    {
        return new AGenericTypes(
            cloneNode(this._type_),
            cloneList(this._additionalTypes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGenericTypes(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public LinkedList<PAdditionalTypes> getAdditionalTypes()
    {
        return this._additionalTypes_;
    }

    public void setAdditionalTypes(List<PAdditionalTypes> list)
    {
        this._additionalTypes_.clear();
        this._additionalTypes_.addAll(list);
        for(PAdditionalTypes e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._additionalTypes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._additionalTypes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        for(ListIterator<PAdditionalTypes> i = this._additionalTypes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAdditionalTypes) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
