/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AIsaInstr extends PInstr
{
    private PType _left_;
    private TKisa _kisa_;
    private PType _right_;

    public AIsaInstr()
    {
        // Constructor
    }

    public AIsaInstr(
        @SuppressWarnings("hiding") PType _left_,
        @SuppressWarnings("hiding") TKisa _kisa_,
        @SuppressWarnings("hiding") PType _right_)
    {
        // Constructor
        setLeft(_left_);

        setKisa(_kisa_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AIsaInstr(
            cloneNode(this._left_),
            cloneNode(this._kisa_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIsaInstr(this);
    }

    public PType getLeft()
    {
        return this._left_;
    }

    public void setLeft(PType node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TKisa getKisa()
    {
        return this._kisa_;
    }

    public void setKisa(TKisa node)
    {
        if(this._kisa_ != null)
        {
            this._kisa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kisa_ = node;
    }

    public PType getRight()
    {
        return this._right_;
    }

    public void setRight(PType node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._kisa_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._kisa_ == child)
        {
            this._kisa_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PType) newChild);
            return;
        }

        if(this._kisa_ == oldChild)
        {
            setKisa((TKisa) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
