/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ANewInstr extends PInstr
{
    private TKnew _knew_;
    private PType _type_;

    public ANewInstr()
    {
        // Constructor
    }

    public ANewInstr(
        @SuppressWarnings("hiding") TKnew _knew_,
        @SuppressWarnings("hiding") PType _type_)
    {
        // Constructor
        setKnew(_knew_);

        setType(_type_);

    }

    @Override
    public Object clone()
    {
        return new ANewInstr(
            cloneNode(this._knew_),
            cloneNode(this._type_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANewInstr(this);
    }

    public TKnew getKnew()
    {
        return this._knew_;
    }

    public void setKnew(TKnew node)
    {
        if(this._knew_ != null)
        {
            this._knew_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._knew_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._knew_)
            + toString(this._type_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._knew_ == child)
        {
            this._knew_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._knew_ == oldChild)
        {
            setKnew((TKnew) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
