/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ASuperGenericPart extends PSuperGenericPart
{
    private TLb _lb_;
    private PSuperGenericTypes _superGenericTypes_;
    private TRb _rb_;

    public ASuperGenericPart()
    {
        // Constructor
    }

    public ASuperGenericPart(
        @SuppressWarnings("hiding") TLb _lb_,
        @SuppressWarnings("hiding") PSuperGenericTypes _superGenericTypes_,
        @SuppressWarnings("hiding") TRb _rb_)
    {
        // Constructor
        setLb(_lb_);

        setSuperGenericTypes(_superGenericTypes_);

        setRb(_rb_);

    }

    @Override
    public Object clone()
    {
        return new ASuperGenericPart(
            cloneNode(this._lb_),
            cloneNode(this._superGenericTypes_),
            cloneNode(this._rb_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuperGenericPart(this);
    }

    public TLb getLb()
    {
        return this._lb_;
    }

    public void setLb(TLb node)
    {
        if(this._lb_ != null)
        {
            this._lb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lb_ = node;
    }

    public PSuperGenericTypes getSuperGenericTypes()
    {
        return this._superGenericTypes_;
    }

    public void setSuperGenericTypes(PSuperGenericTypes node)
    {
        if(this._superGenericTypes_ != null)
        {
            this._superGenericTypes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._superGenericTypes_ = node;
    }

    public TRb getRb()
    {
        return this._rb_;
    }

    public void setRb(TRb node)
    {
        if(this._rb_ != null)
        {
            this._rb_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rb_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lb_)
            + toString(this._superGenericTypes_)
            + toString(this._rb_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lb_ == child)
        {
            this._lb_ = null;
            return;
        }

        if(this._superGenericTypes_ == child)
        {
            this._superGenericTypes_ = null;
            return;
        }

        if(this._rb_ == child)
        {
            this._rb_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lb_ == oldChild)
        {
            setLb((TLb) newChild);
            return;
        }

        if(this._superGenericTypes_ == oldChild)
        {
            setSuperGenericTypes((PSuperGenericTypes) newChild);
            return;
        }

        if(this._rb_ == oldChild)
        {
            setRb((TRb) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
