/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ASuperAdditionalTypes extends PSuperAdditionalTypes
{
    private TComma _comma_;
    private PSuperType _superType_;

    public ASuperAdditionalTypes()
    {
        // Constructor
    }

    public ASuperAdditionalTypes(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PSuperType _superType_)
    {
        // Constructor
        setComma(_comma_);

        setSuperType(_superType_);

    }

    @Override
    public Object clone()
    {
        return new ASuperAdditionalTypes(
            cloneNode(this._comma_),
            cloneNode(this._superType_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuperAdditionalTypes(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PSuperType getSuperType()
    {
        return this._superType_;
    }

    public void setSuperType(PSuperType node)
    {
        if(this._superType_ != null)
        {
            this._superType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._superType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._superType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._superType_ == child)
        {
            this._superType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._superType_ == oldChild)
        {
            setSuperType((PSuperType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
