/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ASuperType extends PSuperType
{
    private TName _name_;
    private PSuperGenericPart _superGenericPart_;

    public ASuperType()
    {
        // Constructor
    }

    public ASuperType(
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") PSuperGenericPart _superGenericPart_)
    {
        // Constructor
        setName(_name_);

        setSuperGenericPart(_superGenericPart_);

    }

    @Override
    public Object clone()
    {
        return new ASuperType(
            cloneNode(this._name_),
            cloneNode(this._superGenericPart_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuperType(this);
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PSuperGenericPart getSuperGenericPart()
    {
        return this._superGenericPart_;
    }

    public void setSuperGenericPart(PSuperGenericPart node)
    {
        if(this._superGenericPart_ != null)
        {
            this._superGenericPart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._superGenericPart_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._superGenericPart_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._superGenericPart_ == child)
        {
            this._superGenericPart_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._superGenericPart_ == oldChild)
        {
            setSuperGenericPart((PSuperGenericPart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
