/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import java.util.*;
import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ASuperGenericTypes extends PSuperGenericTypes
{
    private PSuperType _superType_;
    private final LinkedList<PSuperAdditionalTypes> _superAdditionalTypes_ = new LinkedList<PSuperAdditionalTypes>();

    public ASuperGenericTypes()
    {
        // Constructor
    }

    public ASuperGenericTypes(
        @SuppressWarnings("hiding") PSuperType _superType_,
        @SuppressWarnings("hiding") List<PSuperAdditionalTypes> _superAdditionalTypes_)
    {
        // Constructor
        setSuperType(_superType_);

        setSuperAdditionalTypes(_superAdditionalTypes_);

    }

    @Override
    public Object clone()
    {
        return new ASuperGenericTypes(
            cloneNode(this._superType_),
            cloneList(this._superAdditionalTypes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuperGenericTypes(this);
    }

    public PSuperType getSuperType()
    {
        return this._superType_;
    }

    public void setSuperType(PSuperType node)
    {
        if(this._superType_ != null)
        {
            this._superType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._superType_ = node;
    }

    public LinkedList<PSuperAdditionalTypes> getSuperAdditionalTypes()
    {
        return this._superAdditionalTypes_;
    }

    public void setSuperAdditionalTypes(List<PSuperAdditionalTypes> list)
    {
        this._superAdditionalTypes_.clear();
        this._superAdditionalTypes_.addAll(list);
        for(PSuperAdditionalTypes e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._superType_)
            + toString(this._superAdditionalTypes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._superType_ == child)
        {
            this._superType_ = null;
            return;
        }

        if(this._superAdditionalTypes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._superType_ == oldChild)
        {
            setSuperType((PSuperType) newChild);
            return;
        }

        for(ListIterator<PSuperAdditionalTypes> i = this._superAdditionalTypes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PSuperAdditionalTypes) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
