/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class ATypeInstr extends PInstr
{
    private TKtype _ktype_;
    private PExp _exp_;

    public ATypeInstr()
    {
        // Constructor
    }

    public ATypeInstr(
        @SuppressWarnings("hiding") TKtype _ktype_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setKtype(_ktype_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new ATypeInstr(
            cloneNode(this._ktype_),
            cloneNode(this._exp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeInstr(this);
    }

    public TKtype getKtype()
    {
        return this._ktype_;
    }

    public void setKtype(TKtype node)
    {
        if(this._ktype_ != null)
        {
            this._ktype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ktype_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ktype_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ktype_ == child)
        {
            this._ktype_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ktype_ == oldChild)
        {
            setKtype((TKtype) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
