/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class AType extends PType
{
    private TName _name_;
    private PGenericPart _genericPart_;

    public AType()
    {
        // Constructor
    }

    public AType(
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") PGenericPart _genericPart_)
    {
        // Constructor
        setName(_name_);

        setGenericPart(_genericPart_);

    }

    @Override
    public Object clone()
    {
        return new AType(
            cloneNode(this._name_),
            cloneNode(this._genericPart_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAType(this);
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PGenericPart getGenericPart()
    {
        return this._genericPart_;
    }

    public void setGenericPart(PGenericPart node)
    {
        if(this._genericPart_ != null)
        {
            this._genericPart_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._genericPart_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._genericPart_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._genericPart_ == child)
        {
            this._genericPart_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._genericPart_ == oldChild)
        {
            setGenericPart((PGenericPart) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
