/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TKisa extends Token
{
    public TKisa()
    {
        super.setText("isa");
    }

    public TKisa(int line, int pos)
    {
        super.setText("isa");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKisa(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKisa(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKisa text.");
    }
}
