/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TKnew extends Token
{
    public TKnew()
    {
        super.setText("new");
    }

    public TKnew(int line, int pos)
    {
        super.setText("new");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKnew(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKnew(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKnew text.");
    }
}
