/* This file was generated by SableCC (http://www.sablecc.org/). */

package minigen.syntax3.node;

import minigen.syntax3.analysis.*;

@SuppressWarnings("nls")
public final class TKvar extends Token
{
    public TKvar()
    {
        super.setText("var");
    }

    public TKvar(int line, int pos)
    {
        super.setText("var");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKvar(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKvar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKvar text.");
    }
}
